# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../modules/wayland/sway.nix
    ../modules/display-manager/regreet
    ./common-real.nix
  ];

  networking.hostName = "snowfox";
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  security.tpm2 = {
    enable = true;
    pkcs11.enable = true;
  };
  services.logind.settings.Login.HandleLidSwitch = "suspend";

  boot = {
    lanzaboote = {
      enable = true;
      pkiBundle = "/var/lib/sbctl";
    };
    loader.systemd-boot.enable = false;
  };

  environment.systemPackages = with pkgs; [
    sbctl
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c2defd28-93d8-4329-8d51-1cefa4f17adb";
    fsType = "btrfs";
    options = [ "subvol=nixos" ];
  };

  services = {
    xserver.xkb.layout = "de";
    btrfs.autoScrub = {
      enable = true;
      fileSystems = [ "/" ];
      interval = "weekly";
    };
    fprintd = {
      enable = true;
    };
  };

  boot.initrd = {
    luks.devices."root" = {
      device = "/dev/disk/by-uuid/a1b31149-1077-4ea7-907d-045a912f1f3b";
      preLVM = true;
    };
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EB4A-AD57";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    enableAllFirmware = true;
    keyboard.qmk.enable = true;
    bluetooth = {
      enable = true;
      package = pkgs.bluez;
    };
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        libva
        libva-utils
      ];
    };
  };

  powerManagement = {
    enable = true;
    powertop = {
      enable = true;
    };
  };
  services.auto-cpufreq = {
    enable = true;
    settings = {
      battery = {
        governor = "powersave";
        turbo = "never";
      };
      charger = {
        governor = "performance";
        turbo = "auto";
      };
    };
  };
}
