# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../modules/wayland/sway.nix
    # ../modules/wayland/somewm.nix
    ../modules/wayland/niri.nix
    ../modules/display-manager/regreet
    ./common-real.nix
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c2defd28-93d8-4329-8d51-1cefa4f17adb";
    fsType = "btrfs";
    options = [ "subvol=nixos" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EB4A-AD57";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  boot = {
    initrd = {
      luks.devices."root" = {
        device = "/dev/disk/by-uuid/a1b31149-1077-4ea7-907d-045a912f1f3b";
        preLVM = true;
      };
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    kernelParams = [ ];
    extraModulePackages = [ ];
    lanzaboote = {
      enable = true;
      pkiBundle = "/var/lib/sbctl";
    };
    loader.systemd-boot.enable = false;
  };

  security.tpm2 = {
    enable = true;
    pkcs11.enable = true;
  };

  environment.systemPackages = with pkgs; [
    sbctl
  ];

  networking.hostName = "snowfox";

  services = {
    logind.settings.Login.HandleLidSwitch = "suspend";
    nix-serve = {
      enable = true;
      package = pkgs.nix-serve-ng;
      openFirewall = true;
      secretKeyFile = "/etc/nix/serve-secret";
    };
    xserver.xkb.layout = "de";
    btrfs.autoScrub = {
      enable = true;
      fileSystems = [ "/" ];
      interval = "weekly";
    };
    fprintd = {
      enable = true;
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    enableAllFirmware = true;
    keyboard.qmk.enable = true;
    bluetooth = {
      enable = true;
      package = pkgs.bluez;
    };
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        libva
        libva-utils
      ];
    };
  };

  powerManagement = {
    enable = true;
    powertop = {
      enable = true;
    };
  };
  services.auto-cpufreq = {
    enable = true;
    settings = {
      battery = {
        governor = "powersave";
        turbo = "never";
      };
      charger = {
        governor = "performance";
        turbo = "auto";
      };
    };
  };
  # noita
  programs.steam.enable = true;
}
